_tau::build_py_shim_body() {
  # Outside a virtual environment, run only inline code (-c or -) and only
  # against the standard library; refuse scripts, modules and the REPL.
  cat <<'EOF'
#!/usr/bin/env bash
# Generated by `tau rehash`. Outside a virtual environment this shim runs only
# inline code (-c CODE, or - for stdin), isolated from PYTHON* variables, the
# user site and every site-packages (-I -S), so only the standard library can
# be imported. Scripts, modules (-m, pip included) and the REPL are refused.

_red_bold() { echo -e "\033[1;31m$*\033[0m" >&2; }

_real_python() {
  # The next interpreter with this shim's name on PATH, skipping the shims
  # directory; a bare `python` falls back to `python3`.
  local shims_dir="${BASH_SOURCE[0]%/*}" name dir
  local -a names dirs
  names=("${0##*/}")
  [[ "${0##*/}" == python ]] && names+=(python3)
  IFS=: read -r -a dirs <<< "${PATH}"
  for name in "${names[@]}"; do
    for dir in "${dirs[@]}"; do
      [[ -z "${dir}" || "${dir}" -ef "${shims_dir}" ]] && continue
      if [[ -f "${dir}/${name}" && -x "${dir}/${name}" ]]; then
        echo "${dir}/${name}"
        return 0
      fi
    done
  done
  _red_bold "[tau.error] No '${0##*/}' interpreter found on PATH outside the tau shims."
  return 1
}

case "${1-}" in
  -c | -)
    real="$(_real_python)" || exit 1
    exec "${real}" -I -S "$@"
    ;;
  --version | -V)
    real="$(_real_python)" || exit 1
    exec "${real}" "$@"
    ;;
esac

_red_bold "[tau.error] Outside a virtual environment, python only runs inline code (-c or -), limited to the standard library."
_red_bold "[tau.error] For scripts, modules and packages, activate a virtual environment or use 'uv run python ...' (in tomasv-docs: bin/uv-run python ...)."
exit 1
EOF
}

_tau::build_pip_shim_body() {
  echo "#!/usr/bin/env bash"
  echo ""
  # shellcheck disable=SC2028
  echo "_red_bold() { echo -e \"\033[1;31m\$*\033[0m\" >&2; }"
  echo ""
  echo "_red_bold \"[tau.error] It looks like you're trying to run 'pip' outside of a virtual environment.\""
  echo "_red_bold \"[tau.error] Please activate a virtual environment and try again, or consider using uvx for global installations.\""
  echo ""
  echo "exit 1"
  echo ""
}

_tau::write_py_shim() {
  local shim_suffix shim_name shim_dest
  shim_suffix="${1}"
  shim_name="python${shim_suffix}"
  shim_dest="${TAU_ROOT}/shims/$shim_name"
  _tau::build_py_shim_body > "${shim_dest}"
  chmod +x "${shim_dest}"
}

_tau::write_pip_shim() {
  local shim_suffix shim_name shim_dest
  shim_suffix="${1}"
  shim_name="pip${shim_suffix}"
  shim_dest="${TAU_ROOT}/shims/$shim_name"
  _tau::build_pip_shim_body > "${shim_dest}"
  chmod +x "${shim_dest}"
}

tau-rehash() {
  # Usage: tau rehash
  #
  # Regenerate python and pip shims for all installed Python versions
  #
  local py_installed_versions py_versions pyv_minor
  _tau::mk_root_dir
  # shellcheck disable=SC2296
  py_installed_versions=("${(@s: :)"$(tau-versions --squash)"}")
  for py_versions in "${py_installed_versions[@]}"; do
    pyv_minor="$(echo "${py_versions}" | _tau::patch_to_minor)"
    _tau::write_py_shim "${pyv_minor}"
    _tau::write_pip_shim "${pyv_minor}"
  done
  # Also create shims for 'python', 'python3', 'pip', and 'pip3'
  _tau::write_pip_shim ""
  _tau::write_pip_shim "3"
  _tau::write_py_shim ""
  _tau::write_py_shim "3"
}
