# Description: Enable Touch ID for sudo authentication

# GNU's grep is needed for this script to work properly
ggrep="$HOMEBREW_PREFIX/bin/ggrep"
if ! command -v "${ggrep}" &>/dev/null; then
  brew install grep
  # (recursively) call this script again to ensure the new grep is used
  source "${0}"
fi

__config_file="/etc/pam.d/sudo_local"
__config_line="auth       sufficient     pam_tid.so"
__config_line_escaped="$(printf '%q' "${__config_line}")"
__config_file_contents="# -------------------------------------------------------------------
# This file was generated by the bootstrap script at:
# https://github.com/tpvasconcelos/dotfiles
#
# It enables Touch ID for sudo authentication.
#
# The implementation is based on macOS Sonoma's release notes:
# https://support.apple.com/en-gb/109030
#
# and the following StackExchange answer:
# https://apple.stackexchange.com/a/466029
#
# -------------------------------------------------------------------

${__config_line}
"

__SE_ref="https://apple.stackexchange.com/q/259093"

__check_sudo_touchid_configured() {
  if ! [[ -r "${__config_file}" ]] || ! sudo ggrep -q "${__config_line}" "${__config_file}"; then
    # The file doesn't exist or the expected line is not present
    return 1
  fi

  # Check whether the expected line exists but is commented out...
  if sudo ggrep -qP "^#+[[:space:]]*${__config_line_escaped}" "${__config_file}"; then
    log_warning "The expected config line in ${__config_file} seems to be commented out!
    Please uncomment the '''${__config_line}''' line or refer
    to ${__SE_ref} for more detailed instructions."
    return 1
  fi

  return 0
}


if __check_sudo_touchid_configured; then
  log_success "Touch ID for sudo is already enabled!"
else
  echo
  if ask-yesno "$(green-bold "Would you like to enable Touch ID for sudo?")"; then
    if [[ -r "${__config_file}" ]]; then
      log_error "Aborting...\nCustom PAM configuration found at: ${__config_file}\nPlease refer to https://apple.stackexchange.com/q/259093 for manual instructions."
      echo
    else
      log_info "Enabling Touch ID for sudo..."
      echo "${__config_file_contents}" | sudo tee "${__config_file}" >/dev/null
      log_success "Touch ID for sudo is now enabled!"
    fi
  fi
fi
